django_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


from django_project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shoppy/', include('shoppy.urls')),
    path('shoppyadmin/', include('shoppyadmin.urls')),
    path('rest_auth/', include('rest_auth.urls')),
    path('rest_auth/registration/', include('rest_auth.registration.urls')),
    path('android/', include('androidAuthApi.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),





]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shoppy/urls.py
from django.conf.urls import url
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetCompleteView, \
   PasswordResetDoneView
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views


app_name = 'Shoppy'
urlpatterns =[
   # path('', views.setcookie),
   path('home/', views.home, name='shoppy-home'),
   path('cart/', views.cart, name='shoppy-cart'),
   path('register/', views.buyer_register, name='shoppy-buyer-reg'),
   path('seller_register/', views.seller_register, name='shoppy-seller-reg'),
   path('login/', views.user_login, name='shoppy-login'),
   path('logout/', views.logout_view, name='shoppy-logout'),
   path('products_list', views.productsList, name='product_list'),
   path('seller_home/' , views.seller_home, name='shoppy-seller-home' ),
   path('user_account/' , views.user_account, name='shoppy-user_account' ),
   path('checkout/' , views.checkout, name='shoppy-view_checkout' ),
   path('search/' , views.search, name="searchbar" ),




   #wishlist
   path('add_to_wishlist/<int:product_id>/<str:source>' , views.addToWishlist, name='add_to_wishlist' ),
   path('remove_from_wishlist/<int:wishlist_id>/<str:source>' , views.unWishProduct, name='remove_from_wishlist' ), #delete wishlist/unwished
   path('remove_from_wishlist/all/' , views.unWish_All_Products, name='remove_all_from_wishlist' ), #delete all wishlist/unwished

   #view product details
   path('details/<int:product_id>/', views.productDetails, name='shoppy_product_details'),
         # reviews
         path('reviews/<int:product_id>/', views.productReview, name='shoppy_product_review'),

   #cart
   path('cart/', views.cart, name='shoppy-cart'),
   path('addto/cart/<int:product_id>/', views.addCart, name='shoppy-add-cart'),
   path('deletefrom/cart/<int:order_id>/', views.deleteCartProduct, name='shoppy_delete_cart_product'),

   # checkout
   path('confirmcheckout/', views.confirmCheckout, name='shoppy-checkout'),

   # useraccount password change
   path('user_account/change_password', views.change_password, name='change_password'),

   # password reset





   path('password_reset/', auth_views.PasswordResetView.as_view(
      template_name='shoppy/registration/password_reset.html',
      email_template_name='shoppy/registration/password_reset_email.html',
      subject_template_name='shoppy/registration/password_reset_subject.txt',
      success_url=reverse_lazy('Shoppy:password_reset_done')
   ), name='password_reset'),

   path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
      template_name='shoppy/registration/password_reset_done.html',
   ), name='password_reset_done'),

   path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
      template_name='shoppy/registration/password_reset_confirm.html',
      success_url=reverse_lazy('Shoppy:password_reset_complete')
   ), name='password_reset_confirm'),

   path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(
      template_name='shoppy/registration/password_reset_complete.html',
   ), name='password_reset_complete'),







]

shoppyadmin/urls.py
from django.urls import path
from .views import GeneratePDF, ListUsers, GenerateProductPDF, ListOrders

from . import views

app_name = 'ShoppyAdmin'
urlpatterns = (

   path('home/', views.home, name='shoppy-admin-home'),
   path('sellers/', views.sellers, name='shoppy-admin-sellers'),
   path('orders/', views.orders, name='shoppy-admin-orders'),
   path('login/', views.user_login, name='shoppy-admin-login'),
   path('all/productsreviews/', views.reviews, name='shoppy-admin-reviews'),
   path('singleproduct/review/<int:product_id>/', views.single_product_review, name='single_product_review'),
   path('buyers/', views.buyers, name='shoppy-admin-buyers'),
   path('useraccount/', views.userAccount, name='shoppy-user-account'),
   path('useraccount/changepassword/', views.changepassword, name='shoppy-changepassword'),
   path('payments/', views.payments, name='shoppy-payments'),
     # extras
      path('pdf/orders/', GeneratePDF.as_view(), name='orders_generated_pdf'),
      path('productspdf/', GenerateProductPDF.as_view(), name='products_generated_pdf'),
      path('users/chart/', ListUsers.as_view(), name='users_chart'),
      path('orders/chart/', ListOrders.as_view(), name='orders_chart'),
     # extras
   # seller
   path('seller_status/<int:seller_id>', views.sellerStatusChange, name='shoppy-admin-status-change'),

   #products
   path('view/products/', views.view_all_products, name="shoppy_admin_view_all_products"),
   path('edit/product/<int:product_id>', views.edit_product, name="shoppy_admin_edit_product"),
   path('delete/product/<int:product_id>', views.product_delete, name='product_delete'),

   #featuredProducts
   path('products/featured/products', views.featured_products, name='featured_products'),
   path('featured/product/change/status/featured/<int:product_id>', views.featured_products_featured, name='featured_products'),
   path('featured/product/change/status/normal/<int:product_id>', views.normal_products_normal, name='nomal_products'),

   #category
   path('view_category/', views.view_category, name='shoppy_admin_add_category'),
   path('addingcategory/', views.addingcategory, name='shoppy_adding_category'),
   path('deletecategory/<int:category_id>', views.deletecategory, name='shoppy_delete_category'),
   path('editcategory/<int:category_id>', views.editcategory, name='shoppy_edit_category'),
   path('view_sub_category/<int:category_id>', views.view_sub_category, name='shoppy_view_sub_category'),


   # brand
   path('add_brand/', views.add_brand, name='shoppy_admin_add_brand'),
   path('delete/brand/<int:brand_id>', views.brand_delete, name='delete_brand'),
   path('edit/brand/<int:brand_id>', views.brand_edit, name='brand_edit'),

   #image
   path('delete/image/<int:image_id>', views.image_delete, name='delete_product_image'),

   #regions
   path('viewregions/', views.view_regions, name='shoppy-admin-view-regions'),
   path('regions/edit/<int:region_id>', views.edit_regions, name='shoppy-admin-edit-regions'),
   path('regions/delete/<int:region_id>', views.delete_regions, name='shoppy-admin-delete-regions'),

   #carousell
   path('view/carousel/', views.view_carousel, name='view_carousel'),
   path('carousel/delete/<int:carousel_id>', views.carousel_delete, name='carousel-delete'),

   #variants
   path('variants/', views.variants, name='variants'),
   path('variants/delete/<int:variant_id>', views.variant_delete, name='variant_delete'),
   path('variants/edit/<int:variant_id>', views.variant_edit, name='variant_edit'),

   #variant options
   path('variantsOptions/add/', views.variants_options, name='variants-options'),
   path('variantsOptions/delete/<int:variant_option_id>', views.variants_options_delete, name='variants-options-delete'),
   path('variantsOptions/edit/<int:variant_option_id>', views.variants_options_edit, name='variants-options-edit'),

   # offer
   path('offers/', views.offer, name='view_product_offer'),
   path('addOffer/',views.addOffer, name="adding_offers"),
   path('editOffer/<int:offer_id>',views.editOffer, name="edit_offers"),
   path('deleteOffer/<int:offer_id>',views.deleteOffer, name="delete_offer"),

   # reports
   path('allreports/', views.viewAllReports, name='view_all_reports'),
)

shoppyadmin/models.py
from django.db import models

# Create your models here.

shoppyadmin/templates/products/carousel.html
{% extends 'aaa_layout.html' %}
{% load static %}
{% block links %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css" rel="stylesheet" />

{% endblock links %}
{% block content %}
     <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
		<div class="row">
			<ol class="breadcrumb">
				<li>
					<a href="#">
					<em class="fa fa-home"></em>
				    </a>
			    </li>
				<li class="active">Product / Carousel</li>
			</ol>
		</div><!--/.row-->
        <div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Carousel</h1>
			</div>
		</div><!--/.row-->

        <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading panel-warning-custom">
                            Add Carousel Image
                            <ul class="pull-right panel-settings panel-button-tab-right">
                                <li class="dropdown"><a class="pull-right dropdown-toggle" data-toggle="dropdown" href="#">
                                    <em class="fa fa-cogs"></em>
                                </a>
                                    <ul class="dropdown-menu dropdown-menu-right">
                                        <li>
                                            <ul class="dropdown-settings">
                                                <li><a href="#">
                                                    <em class="fa fa-cog"></em> Settings 1
                                                </a></li>
                                                <li class="divider"></li>
                                                <li><a href="#">
                                                    <em class="fa fa-cog"></em> Settings 2
                                                </a></li>
                                                <li class="divider"></li>
                                                <li><a href="#">
                                                    <em class="fa fa-cog"></em> Settings 3
                                                </a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                            <span class="pull-right clickable panel-toggle panel-button-tab-left"><em class="fa fa-toggle-up"></em></span></div>
                        <div class="panel-body">
                            <div class="canvas-wrapper">
                                <div class="main-chart col-sm-12" id="line-chart" height="200" width="600">
                                    <form action="{% url 'ShoppyAdmin:view_carousel' %}" method="POST" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <div class="input-group col-sm-12 marginY" >
                                           <div class="form-group">
                                                <label class="custom-control" for="email">Description:</label>
                                                <input placeholder="Brief Description" name="description" type="text" class="form-control" id="email">
                                           </div>
                                        </div>
                                        <div class="input-group col-sm-12 marginY">
                                           <div class="form-group">
                                                <label class="custom-control" for="image">Choose A File</label>
                                                <input name="image"  type="file" class="form-control" id="image" required>
                                           </div>
                                        </div>
                                        <button type="submit" class="btn btn-success marginY"><i class="fas fa-plus-circle"></i> Add</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--/.row-->
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading panel-warning-custom">
                        Carousell Images ({% if carousels %} {{ carousels.count }} {% endif %})
                        <ul class="pull-right panel-settings panel-button-tab-right">
                            <li class="dropdown"><a class="pull-right dropdown-toggle" data-toggle="dropdown" href="#">
                                <em class="fa fa-cogs"></em>
                            </a>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li>
                                        <ul class="dropdown-settings">
                                            <li><a href="#">
                                                <em class="fa fa-cog"></em> Settings 1
                                            </a></li>
                                            <li class="divider"></li>
                                            <li><a href="#">
                                                <em class="fa fa-cog"></em> Settings 2
                                            </a></li>
                                            <li class="divider"></li>
                                            <li><a href="#">
                                                <em class="fa fa-cog"></em> Settings 3
                                            </a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                        <span class="pull-right clickable panel-toggle panel-button-tab-left"><em class="fa fa-toggle-up"></em></span></div>
                    <div class="panel-body">
                        <div class="canvas-wrapper">
                            <div class="main-chart col-sm-12" id="line-chart" height="200" width="600">
                                <table id="example" class="example table table-striped table-bordered" style="width:100%;">
                                    <thead>
                                        <tr class="text-capitalize">
                                            <th>Id</th>
                                            <th>Carousel</th>
                                            <th>Description</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for carousel in carousels %}
                                            <tr class="text-center ">
                                                <td class="tb-data" width="50">{{ carousel.id }}</td>
                                                <td class="tb-data carousel-table">
                                                    <div class="carousel-wrapper">
                                                        <a href="{{ carousel.image.url }}"><img src="../../..{{ carousel.image.url }}" alt=""></a>

                                                    </div>
                                                </td>
                                                <td class="tb-data-desc">
                                                    <h4  style="text-transform:uppercase">{{ carousel.description }}</h4>
                                                    <span class="pull-right carousel-date">{{ carousel.created_at }}</span>
                                                </td>
                                                <td class="tb-data" width="150">
                                                    <a href="" class="btn btn-danger" data-toggle="modal" data-target="#{{ carousel.id }}"><i class="fas fa-trash"></i> Delete</a>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                
                                    </tbody>
                                </table>

                            {% for carousel in carousels %}
                                <div id="{{ carousel.id }}" class="modal fade" tabindex="-1" role="dialog">
                                  <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                      <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title">Carousel Delete</h4>
                                      </div>
                                      <div class="modal-body">
                                        <h3><b>Are you sure you want to delete {{ carousel.name }} ! &hellip;</b></h3>
                                      </div>
                                      <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                        <a href="{% url 'ShoppyAdmin:carousel-delete' carousel.id %}" class="btn btn-danger"><i class="fas fa-trash"></i> Delete</a>
                                      </div>
                                    </div><!-- /.modal-content -->
                                  </div><!-- /.modal-dialog -->
                                </div><!-- /.modal -->
                            {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/.row-->
    </div>

{% endblock %}
{% block scripts %}
    <script>
        $(document).ready(function() {
            $('#example').DataTable();
        } );
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/js/bootstrap-select.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap.min.js"></script>
{% endblock scripts %}

shoppyadmin/templates/products/featuredproducts.html
{% extends 'aaa_layout.html' %}
{% load static %}
{% load call_method %}
{% block links %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css" rel="stylesheet" />

{% endblock links %}
{% block content %}
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
		<div class="row">
			<ol class="breadcrumb">
				<li>
					<a href="#">
					<em class="fa fa-home"></em>
				    </a>
			    </li>
				<li class="">Products</li>
				<li class="active">Featured Products</li>
			</ol>
		</div><!--/.row-->
       <div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Featured Products</h1>
			</div>
		</div><!--/.row-->

        <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading panel-warning-custom">
                            Featured Products
                            <span class="pull-right clickable panel-toggle panel-button-tab-left"><em class="fa fa-toggle-up"></em></span></div>
                        <div class="panel-body">
                            <div class="canvas-wrapper">
                                <div class="main-chart" id="line-chart" height="200" width="600">
                                    <table id="" class="example table table-striped table-bordered" style="width:100%;">
                                        <thead>
                                            <tr class="text-capitalize">
                                                <th>Id</th>
                                                <th>Picture</th>
                                                <th>Name</th>
                                                <th>Created At</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for product in products %}
                                                <tr class="text-center ">
                                                    <td class="tb-data">{{ forloop.counter }}</td>
                                                    <td class="tb-data tb-data">
                                                        <div class="product-image">
                                                           <img src="{{ product.featured_url.url }}" alt="{{ product.name }}">
                                                        </div>
                                                    </td>
                                                    <td class="tb-data">{{ product.name }}</td>
                                                    <td class="tb-data">{{ product.created_at }}</td>
                                                    <td class="tb-data">
                                                     {% if not request.user|is_seller %}
                                                        {% if product.status == 'FEATURED' %}
                                                        <a class="btn-primary btn" href="{% url 'ShoppyAdmin:featured_products' product.id %}"><em class="fas fa-trash-alt"></em> {{ product.status }}</a>
                                                        {% else %}
                                                        <a class="btn-brown btn" href="{% url 'ShoppyAdmin:normal_products' product.id %}"><em class="fas fa-trash-alt"></em> {{ product.status }}</a>
                                                        {% endif %}
                                                    {% endif %}
                                                        <a href="{% url 'ShoppyAdmin:shoppy_admin_edit_product' product.id %}" class="btn btn-success"><i class="fas fa-pencil-alt"></i> Edit</a>
                                                    </td>
                                                </tr>
                                            {% endfor %}

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--/.row-->
    </div>
{% endblock %}
{% block scripts %}
    <script>
        $(document).ready(function() {
            $('#example').DataTable();
        } );
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/js/bootstrap-select.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap.min.js"></script>
{% endblock scripts %}