django_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


from django_project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shoppy/', include('shoppy.urls')),
    path('shoppyadmin/', include('shoppyadmin.urls')),
    path('rest_auth/', include('rest_auth.urls')),
    path('rest_auth/registration/', include('rest_auth.registration.urls')),
    path('android/', include('androidAuthApi.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),





]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shoppy/urls.py
from django.conf.urls import url
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetCompleteView, \
   PasswordResetDoneView
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views


app_name = 'Shoppy'
urlpatterns =[
   # path('', views.setcookie),
   path('home/', views.home, name='shoppy-home'),
   path('cart/', views.cart, name='shoppy-cart'),
   path('register/', views.buyer_register, name='shoppy-buyer-reg'),
   path('seller_register/', views.seller_register, name='shoppy-seller-reg'),
   path('login/', views.user_login, name='shoppy-login'),
   path('logout/', views.logout_view, name='shoppy-logout'),
   path('products_list', views.productsList, name='product_list'),
   path('seller_home/' , views.seller_home, name='shoppy-seller-home' ),
   path('user_account/' , views.user_account, name='shoppy-user_account' ),
   path('checkout/' , views.checkout, name='shoppy-view_checkout' ),
   path('search/' , views.search, name="searchbar" ),




   #wishlist
   path('add_to_wishlist/<int:product_id>/<str:source>' , views.addToWishlist, name='add_to_wishlist' ),
   path('remove_from_wishlist/<int:wishlist_id>/<str:source>' , views.unWishProduct, name='remove_from_wishlist' ), #delete wishlist/unwished
   path('remove_from_wishlist/all/' , views.unWish_All_Products, name='remove_all_from_wishlist' ), #delete all wishlist/unwished

   #view product details
   path('details/<int:product_id>/', views.productDetails, name='shoppy_product_details'),
         # reviews
         path('reviews/<int:product_id>/', views.productReview, name='shoppy_product_review'),

   #cart
   path('cart/', views.cart, name='shoppy-cart'),
   path('addto/cart/<int:product_id>/', views.addCart, name='shoppy-add-cart'),
   path('deletefrom/cart/<int:order_id>/', views.deleteCartProduct, name='shoppy_delete_cart_product'),

   # checkout
   path('confirmcheckout/', views.confirmCheckout, name='shoppy-checkout'),

   # useraccount password change
   path('user_account/change_password', views.change_password, name='change_password'),

   # password reset





   path('password_reset/', auth_views.PasswordResetView.as_view(
      template_name='shoppy/registration/password_reset.html',
      email_template_name='shoppy/registration/password_reset_email.html',
      subject_template_name='shoppy/registration/password_reset_subject.txt',
      success_url=reverse_lazy('Shoppy:password_reset_done')
   ), name='password_reset'),

   path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
      template_name='shoppy/registration/password_reset_done.html',
   ), name='password_reset_done'),

   path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
      template_name='shoppy/registration/password_reset_confirm.html',
      success_url=reverse_lazy('Shoppy:password_reset_complete')
   ), name='password_reset_confirm'),

   path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(
      template_name='shoppy/registration/password_reset_complete.html',
   ), name='password_reset_complete'),







]

shoppyadmin/urls.py
from django.urls import path
from .views import GeneratePDF, ListUsers, GenerateProductPDF, ListOrders

from . import views

app_name = 'ShoppyAdmin'
urlpatterns = (

   path('home/', views.home, name='shoppy-admin-home'),
   path('sellers/', views.sellers, name='shoppy-admin-sellers'),
   path('orders/', views.orders, name='shoppy-admin-orders'),
   path('login/', views.user_login, name='shoppy-admin-login'),
   path('all/productsreviews/', views.reviews, name='shoppy-admin-reviews'),
   path('singleproduct/review/<int:product_id>/', views.single_product_review, name='single_product_review'),
   path('buyers/', views.buyers, name='shoppy-admin-buyers'),
   path('useraccount/', views.userAccount, name='shoppy-user-account'),
   path('useraccount/changepassword/', views.changepassword, name='shoppy-changepassword'),
   path('payments/', views.payments, name='shoppy-payments'),
     # extras
      path('pdf/orders/', GeneratePDF.as_view(), name='orders_generated_pdf'),
      path('productspdf/', GenerateProductPDF.as_view(), name='products_generated_pdf'),
      path('users/chart/', ListUsers.as_view(), name='users_chart'),
      path('orders/chart/', ListOrders.as_view(), name='orders_chart'),
     # extras
   # seller
   path('seller_status/<int:seller_id>', views.sellerStatusChange, name='shoppy-admin-status-change'),

   #products
   path('view/products/', views.view_all_products, name="shoppy_admin_view_all_products"),
   path('edit/product/<int:product_id>', views.edit_product, name="shoppy_admin_edit_product"),
   path('delete/product/<int:product_id>', views.product_delete, name='product_delete'),

   #featuredProducts
   path('products/featured/products', views.featured_products, name='featured_products'),
   path('featured/product/change/status/featured/<int:product_id>', views.featured_products_featured, name='featured_products'),
   path('featured/product/change/status/normal/<int:product_id>', views.normal_products_normal, name='nomal_products'),

   #category
   path('view_category/', views.view_category, name='shoppy_admin_add_category'),
   path('addingcategory/', views.addingcategory, name='shoppy_adding_category'),
   path('deletecategory/<int:category_id>', views.deletecategory, name='shoppy_delete_category'),
   path('editcategory/<int:category_id>', views.editcategory, name='shoppy_edit_category'),
   path('view_sub_category/<int:category_id>', views.view_sub_category, name='shoppy_view_sub_category'),


   # brand
   path('add_brand/', views.add_brand, name='shoppy_admin_add_brand'),
   path('delete/brand/<int:brand_id>', views.brand_delete, name='delete_brand'),
   path('edit/brand/<int:brand_id>', views.brand_edit, name='brand_edit'),

   #image
   path('delete/image/<int:image_id>', views.image_delete, name='delete_product_image'),

   #regions
   path('viewregions/', views.view_regions, name='shoppy-admin-view-regions'),
   path('regions/edit/<int:region_id>', views.edit_regions, name='shoppy-admin-edit-regions'),
   path('regions/delete/<int:region_id>', views.delete_regions, name='shoppy-admin-delete-regions'),

   #carousell
   path('view/carousel/', views.view_carousel, name='view_carousel'),
   path('carousel/delete/<int:carousel_id>', views.carousel_delete, name='carousel-delete'),

   #variants
   path('variants/', views.variants, name='variants'),
   path('variants/delete/<int:variant_id>', views.variant_delete, name='variant_delete'),
   path('variants/edit/<int:variant_id>', views.variant_edit, name='variant_edit'),

   #variant options
   path('variantsOptions/add/', views.variants_options, name='variants-options'),
   path('variantsOptions/delete/<int:variant_option_id>', views.variants_options_delete, name='variants-options-delete'),
   path('variantsOptions/edit/<int:variant_option_id>', views.variants_options_edit, name='variants-options-edit'),

   # offer
   path('offers/', views.offer, name='view_product_offer'),
   path('addOffer/',views.addOffer, name="adding_offers"),
   path('editOffer/<int:offer_id>',views.editOffer, name="edit_offers"),
   path('deleteOffer/<int:offer_id>',views.deleteOffer, name="delete_offer"),

   # reports
   path('allreports/', views.viewAllReports, name='view_all_reports'),
)

shoppyadmin/models.py
from django.db import models

# Create your models here.

shoppyadmin/templates/aaa_layout.html
<!DOCTYPE html>
{% load static %}
{% load call_method %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% if title %}
       <title>Shoppy-{{title}}</title>
    {% else %}
        <title>Shoppy</title>
    {% endif %}
    <link rel="icon" type="image/png" href="{% static 'sitelogo/websitetitlelogo.png' %}"/>

    {#    preloader css#}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel="stylesheet" href="{% static 'css/preloadercss/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
    {#end-preloadercss#}
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/datepicker3.css' %}" rel="stylesheet">
	<link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
	<!--Custom Font-->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    {% block links %}

    {% endblock links %}
    <!--[if lt IE 9]>
	<script src="{% static 'js/html5shiv.js' %}"></script>
	<script src="{% static 'js/respond.min.js' %}"></script>
	<![endif]-->
</head>
<body>
    {#preloader#}
    <header class="loader_wrapper">
        <div class='body'>
        <span>
          <span></span>
          <span></span>
          <span></span>
          <span></span>
        </span>
        <div class='base'>
          <span></span>
          <div class='face'></div>
        </div>
      </div>
      <div class='longfazers'>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
      </div>
      <h1 class="loading_text">Loading Shoppy Admin</h1>
    </header>
    {#endpreloader#}
    <div class="col-sm-12 col-md-12 col-lg-12">
         <nav style="margin: 0;" class="navbar navbar-custom navbar-fixed-top" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse"><span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span></button>
				<a class="navbar-brand logo-admin" href="{% url 'ShoppyAdmin:shoppy-admin-home' %}">
                    <img src="{% static 'sitelogo/shoppy.png' %}" alt="">
                </a>
                <div class="dropdown pull-right">
                  <button style="" class="username dropdown-toggle " type="button" data-toggle="dropdown">
                      {% if request.user.is_authenticated %}
                        HI {{ request.user.first_name }}
                      {% else %}
                        <span class="">
                            <i class="fas fa-user-alt"></i>
                        </span>
                      {% endif %}
                      <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu dropdown-menu-custom" role="menu" aria-labelledby="menu1">
                    <li role="presentation" ><a class="" role="menuitem" href="{% url 'ShoppyAdmin:shoppy-user-account' %}">My account</a></li>
                    <li role="presentation" ><a class="" role="menuitem" href="{% url 'ShoppyAdmin:shoppy-changepassword' %}">Change Password</a></li>
                    <li role="presentation" class="divider"></li>
                    <li role="presentation"><a  class="btn login-btn color-white" role="menuitem" href="{% url 'Shoppy:shoppy-logout' %}">Logout</a></li>
                  </ul>
                </div>
			</div>
		</div><!-- /.container-fluid -->
	</nav>
    </div>

	<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
		<div class="profile-sidebar ">
			<div class="profile-userpic mt-4">
				<img src="http://placehold.it/50/30a5ff/fff" class="img-responsive" alt="">
			</div>
			<div class="profile-usertitle">
				<div class="profile-usertitle-name">
                    {% if request.user.is_authenticated %}
                        HI {{ request.user.first_name }}
                      {% else %}
                        <span class="">
                            Username
                        </span>
                      {% endif %}
                </div>
				<div class="profile-usertitle-status">
                    {% if request.user.is_authenticated %}
                        <span class="indicator label-success"></span>
                        Online
                    {% else %}
                        <span class="indicator label-primary"></span>
                        Offline
                    {% endif %}
                </div>
			</div>
			<div class="clear"></div>
		</div>
		<div class="divider"></div>
		<form role="search">
			<div class="form-group">
				<input type="text" class="form-control" placeholder="Search">
			</div>
		</form>
		<ul class="nav menu">
            <li><a href="{%  url 'ShoppyAdmin:shoppy-admin-home' %}"><em class="fas fa-tachometer-alt">&nbsp;</em> Dashboard</a></li>
			<li class="parent">
                <a  data-toggle="collapse" href="#productssubmenus">
				     <em class="fas  fa-capsules ">&nbsp;</em>
                        Products
                     <span data-toggle="collapse" href="#productssubmenus" class="icon pull-right">
                         <em class="fa fa-plus"></em>
                     </span>
				</a>
				<ul class="children collapse" id="productssubmenus">
					<li><a class="" href="{% url 'ShoppyAdmin:shoppy_admin_view_all_products' %}">
						<span class="fa fa-arrow-right">&nbsp;</span> View Products
					</a></li>
					<li><a class="" href="{% url 'ShoppyAdmin:featured_products' %}">
						<span class="fa fa-arrow-right">&nbsp;</span> Featured Products
					</a></li>
                    <li><a class="" href="{% url 'ShoppyAdmin:view_product_offer' %}">
						<span class="fa fa-arrow-right">&nbsp;</span> Product Offer
					</a></li>
                    {% if not request.user|is_seller %}
                    <li><a class="" href="{% url 'ShoppyAdmin:view_carousel' %}">
						<span class="fa fa-arrow-right">&nbsp;</span> Carousell
					</a></li>
                    {% endif %}
				</ul>
			</li>
            <li class="parent">
                <a data-toggle="collapse" href="#sub-item-3">
				     <em class="fas fa-file-alt">&nbsp;</em>
                        Brands
                     <span data-toggle="collapse" href="#sub-item-3" class="icon pull-right">
                         <em class="fa fa-plus"></em>
                     </span>
				</a>
				<ul class="children collapse" id="sub-item-3">
					<li><a class="" href=" {% url 'ShoppyAdmin:shoppy_admin_add_brand'  %}" >
						<span class="fa fa-arrow-right">&nbsp;</span> View Brands
					</a></li>
				</ul>
			</li>
            <li class="parent">
                <a data-toggle="collapse" href="#sub-item-cat">
				     <em class="fas fa-file-alt">&nbsp;</em>
                        Categories
                     <span data-toggle="collapse" href="#sub-item-3" class="icon pull-right">
                         <em class="fa fa-plus"></em>
                     </span>
				</a>
				<ul class="children collapse" id="sub-item-cat">
					<li><a class="" href="{% url 'ShoppyAdmin:shoppy_admin_add_category' %}" >
						<span class="fa fa-arrow-right">&nbsp;</span> View Categories
					</a></li>
				</ul>
			</li>

            {% if not request.user|is_seller %}
			<li class=""><a href="{%  url 'ShoppyAdmin:shoppy-admin-buyers' %}"><em class="fas fa-user">&nbsp;</em> Buyers</a></li>
			<li class=""><a href="{% url 'ShoppyAdmin:shoppy-admin-sellers' %}"><em class="fas fa-users">&nbsp;</em> Sellers</a></li>
			{% endif %}
            <li class=""><a href="{% url 'ShoppyAdmin:shoppy-admin-orders' %}"><em class="fa fa-toggle-off">&nbsp;</em> Orders</a></li>
			<li class=""><a href="{% url 'ShoppyAdmin:shoppy-admin-view-regions' %}"><em class="fa fa-map-marked">&nbsp;</em> Regions</a></li>
			<li class=""><a href="{% url 'ShoppyAdmin:shoppy-admin-reviews' %}"><em class="fas fa-file-signature">&nbsp;</em> Reviews</a></li>
            <li class=""><a href="{% url 'ShoppyAdmin:shoppy-payments' %}"><em class="fas fa-money-bill-alt">&nbsp;</em> Payments</a></li>

            <li class="parent">
                <a data-toggle="collapse" href="#reports">
				     <em class="fas fa-file-pdf">&nbsp;</em>
                        Reports
                     <span data-toggle="collapse" href="#reports" class="icon pull-right">
                         <em class="fa fa-plus"></em>
                     </span>
				</a>
				<ul class="children collapse" id="reports">
					<li><a class="" href="{% url 'ShoppyAdmin:view_all_reports' %}">
						<span class="fa fa-arrow-right">&nbsp;</span> View Reports
					</a></li>
				</ul>
			</li>
            <li class="parent">
                <a data-toggle="collapse" href="#setting_sub">
				     <em class="fa fa-cog">&nbsp;</em>
                        Settings
                     <span data-toggle="collapse" href="#setting_sub     " class="icon pull-right">
                         <em class="fa fa-plus"></em>
                     </span>
				</a>
				<ul class="children collapse" id="setting_sub">
					<li><a class="" href="{% url 'ShoppyAdmin:variants' %}">
						<span class="fa fa-arrow-right">&nbsp;</span> Variants
					</a></li>
				</ul>
			</li>
			<li class=""><a href="{% url 'Shoppy:shoppy-logout' %}"><em class="fa fa-power-off">&nbsp;</em> Logout</a></li>
		</ul>
	</div><!--/.sidebar-->
    <div style=" position: absolute; z-index: 9;" class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main" >
        <div class="row " style="margin: 10px 0">
                {% if errors %}
                    <ul>
                    {% for error in errors %}
                        <div class="alert alert-{{ error.tags }} alert-dismissible fade in">
                          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                          <strong class="text-white">Error!</strong> {{ error }}
                        </div>
                    {% endfor %}
                    </ul>
                {% endif %}

                {% if messages %}
                    <ul class="messages">
                      {% for message in messages %}
                          <div class="alert alert-{{ message.tags }} alert-dismissible fade in">
                              <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                              <span class="text-white {% if message.tags %} {{ message.tags }}{% endif %}" ><strong>{% if message.tags %} {{ message.tags }}{% endif %}!</strong> {{ message }}</span>
                          </div>
                      {% endfor %}
                    </ul>
                {% endif %}

                {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-{{ error.tags }} alert-dismissible fade in">
                      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                      <strong class="text-white"> {{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}

            {% for error in form.non_field_errors %}
                <div class="alert alert-{{ error.tags }} alert-dismissible fade in">
                  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                  <strong class="text-white"> {{ error|escape }}</strong>
                </div>
            {% endfor %}
          {% endif %}
            </div><!--/.row-->
    </div>
    {% block content %}



    {% endblock %}


	<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
	<script src="{% static 'js/custom.js' %}"></script>
    <script>
       $(window).on("load", function () {

            setTimeout(function(){
               $(".loader_wrapper").removeClass("loadingslideright").addClass("loadingslideleft")
            }, 2000);
        })
    </script>

    {% block scripts %}

    {% endblock %}
</body>
</html>

shoppyadmin/templates/buyers.html
{% extends 'aaa_layout.html' %}
{% load static %}
{% block links %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap.min.css">
{% endblock %}
{% block content %}
		
	<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
		<div class="row">
			<ol class="breadcrumb">
				<li><a href="#">
					<em class="fa fa-home"></em>
				</a></li>
				<li class="active">Buyers</li>
			</ol>
		</div><!--/.row-->
		
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Buyers</h1>
			</div>
		</div><!--/.row-->

		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default articles">
					<div class="panel-heading">
						Buyers
						<ul class="pull-right panel-settings panel-button-tab-right">
							<li class="dropdown"><a class="pull-right dropdown-toggle" data-toggle="dropdown" href="#">
								<em class="fa fa-cogs"></em>
							</a>
								<ul class="dropdown-menu dropdown-menu-right">
									<li>
										<ul class="dropdown-settings">
											<li><a href="#">
												<em class="fa fa-cog"></em> Settings 1
											</a></li>
											<li class="divider"></li>
											<li><a href="#">
												<em class="fa fa-cog"></em> Settings 2
											</a></li>
											<li class="divider"></li>
											<li><a href="#">
												<em class="fa fa-cog"></em> Settings 3
											</a></li>
										</ul>
									</li>
								</ul>
							</li>
						</ul>
						<span class="pull-right clickable panel-toggle panel-button-tab-left"><em class="fa fa-toggle-up"></em></span></div>
					<div class="panel-body articles-container">
                         <div class="canvas-wrapper">
							<div class="main-chart" id="line-chart" height="200" width="600">
                                <table id="example" class="table table-striped table-bordered" style="width:100%;">
                                    <thead >
                                        <tr class="text-capitalize">
                                            <th>Id</th>
                                            <th>Name</th>
                                            <th>Phone_Number</th>
                                            <th>Email</th>
                                            <th>Created_At</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                         {% for buyer in buyers %}
                                            <tr class="text-center ">
                                                <td class="tb-data">{{ buyer.id }}</td>
                                                <td class="product-details">{{ buyer.first_name }} {{ buyer.last_name }}</td>
                                                <td class="tb-data">{{ buyer.phone_number }}</td>
                                                <td class="tb-data">{{ buyer.username }}</td>
                                                <td class="tb-data">{{ buyer.date_joined }}</td>
                                                <td class="text-center tb-data">
                                                    <a href="#" class="btn btn-danger"><i class="fas fa-trash-alt"></i> Delete</a>
                                                    <a href="#" class="btn btn-success"><i class="fas fa-pencil-alt"></i> Edit</a>
                                                </td>
                                            </tr>
                                         {% endfor %}
                                    </tbody>
                                    <tfoot >
                                        <tr class="text-capitalize">
                                            <th>Id</th>
                                            <th>Name</th>
                                            <th>Phone_Number</th>
                                            <th>Email</th>
                                            <th>Created_At</th>
                                            <th>Action</th>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                         </div>
					</div>
				</div><!--End .articles-->

			</div><!--/.col-->




		</div><!--/.row-->
	</div>	<!--/.main-->
	  

{% endblock content %}
{% block scripts %}
    <script>
        $(document).ready(function() {
            $('#example').DataTable();
        } );
    </script>

    <script src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap.min.js"></script>
{% endblock scripts %}

shoppyadmin/templates/sellers.html
{% extends 'aaa_layout.html' %}
{% load static %}
{% block links %}
     <link rel="stylesheet" href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap.min.css">

{% endblock %}
{% block content %}

		
	<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
		<div class="row">
			<ol class="breadcrumb">
				<li><a href="#">
					<em class="fa fa-home"></em>
				</a></li>
				<li class="active">Sellers</li>
			</ol>
		</div><!--/.row-->
		
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Sellers</h1>
			</div>
		</div><!--/.row-->
		
		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						Sellers
						<ul class="pull-right panel-settings panel-button-tab-right">
							<li class="dropdown"><a class="pull-right dropdown-toggle" data-toggle="dropdown" href="#">
								<em class="fa fa-cogs"></em>
							</a>
								<ul class="dropdown-menu dropdown-menu-right">
									<li>
										<ul class="dropdown-settings">
											<li><a href="#">
												<em class="fa fa-cog"></em> Settings 1
											</a></li>
											<li class="divider"></li>
											<li><a href="#">
												<em class="fa fa-cog"></em> Settings 2
											</a></li>
											<li class="divider"></li>
											<li><a href="#">
												<em class="fa fa-cog"></em> Settings 3
											</a></li>
										</ul>
									</li>
								</ul>
							</li>
						</ul>
						<span class="pull-right clickable panel-toggle panel-button-tab-left"><em class="fa fa-toggle-up"></em></span></div>
					<div class="panel-body">
						<div class="canvas-wrapper">
							<div class="main-chart" id="line-chart" height="200" width="600">
                                <table id="example" class="example table table-striped table-bordered" style="width:100%;">
                                    <thead >
                                        <tr class="text-capitalize">
                                            <th>Id</th>
                                            <th>Logo</th>
                                            <th>Name</th>
                                            <th>Business_No</th>
                                            <th>Store_name</th>
                                            <th>Status</th>
                                            <th>County</th>
                                            <th>Created At</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                         {% for seller in seller %}
                                            <tr class="text-center ">
                                                <td class="tb-data">{{ seller.id }}</td>
                                                <td class="tb-data tb-data">
                                                    <div class="store-logo-image">
                                                       <img src="{{ seller.store_logo.url }}" alt="">
                                                    </div>
                                                </td>
                                                <td class="product-details">{{ seller.first_name }} {{ seller.last_name }}</td>
                                                <td class="tb-data">{{ seller.business_no }}</td>
                                                <td class="tb-data">{{ seller.store_name }}</td>
                                                <td class="tb-data">{{ seller.status }}</td>
                                                <td class="tb-data">{{ seller.country }}</td>
                                                <td class="tb-data">{{ seller.date_joined|date:'Y-m-d[H:i]'  }}</td>
                                                <td class="text-center tb-data" width="296">
                                                    <a href="#" class="btn btn-info"><i class="fas fa-eye"></i> View</a>
                                                    <a href="#" class="btn btn-danger"><i class="fas fa-trash-alt"></i> Delete</a>
                                                    {% if seller.status == 'UNVERIFIED' %}
                                                    <a href="{% url 'ShoppyAdmin:shoppy-admin-status-change' seller.id %}" class="btn btn-success"><i class="fas fa-plus"></i> Activate</a>
                                                    {% else %}
                                                    <a href="{% url 'ShoppyAdmin:shoppy-admin-status-change' seller.id %}" class="btn btn-brown"><i class="fas fa-pencil-alt"></i> Deactivate</a>
                                                    {% endif %}
                                                </td>
                                            </tr>
                                         {% endfor %}
                                    </tbody>
                                </table>
                            </div>
						</div>
					</div>
				</div>
			</div>
		</div><!--/.row-->
	</div>	<!--/.main-->
	  




{% endblock %}
{% block scripts %}
    <script>
        $(document).ready(function() {
            $('.example').DataTable();
        } );
    </script>

    <script src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap.min.js"></script>
{% endblock %}