django_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


from django_project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shoppy/', include('shoppy.urls')),
    path('shoppyadmin/', include('shoppyadmin.urls')),
    path('rest_auth/', include('rest_auth.urls')),
    path('rest_auth/registration/', include('rest_auth.registration.urls')),
    path('android/', include('androidAuthApi.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),





]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shoppy/urls.py
from django.conf.urls import url
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetCompleteView, \
   PasswordResetDoneView
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views


app_name = 'Shoppy'
urlpatterns =[
   # path('', views.setcookie),
   path('home/', views.home, name='shoppy-home'),
   path('cart/', views.cart, name='shoppy-cart'),
   path('register/', views.buyer_register, name='shoppy-buyer-reg'),
   path('seller_register/', views.seller_register, name='shoppy-seller-reg'),
   path('login/', views.user_login, name='shoppy-login'),
   path('logout/', views.logout_view, name='shoppy-logout'),
   path('products_list', views.productsList, name='product_list'),
   path('seller_home/' , views.seller_home, name='shoppy-seller-home' ),
   path('user_account/' , views.user_account, name='shoppy-user_account' ),
   path('checkout/' , views.checkout, name='shoppy-view_checkout' ),
   path('search/' , views.search, name="searchbar" ),




   #wishlist
   path('add_to_wishlist/<int:product_id>/<str:source>' , views.addToWishlist, name='add_to_wishlist' ),
   path('remove_from_wishlist/<int:wishlist_id>/<str:source>' , views.unWishProduct, name='remove_from_wishlist' ), #delete wishlist/unwished
   path('remove_from_wishlist/all/' , views.unWish_All_Products, name='remove_all_from_wishlist' ), #delete all wishlist/unwished

   #view product details
   path('details/<int:product_id>/', views.productDetails, name='shoppy_product_details'),
         # reviews
         path('reviews/<int:product_id>/', views.productReview, name='shoppy_product_review'),

   #cart
   path('cart/', views.cart, name='shoppy-cart'),
   path('addto/cart/<int:product_id>/', views.addCart, name='shoppy-add-cart'),
   path('deletefrom/cart/<int:order_id>/', views.deleteCartProduct, name='shoppy_delete_cart_product'),

   # checkout
   path('confirmcheckout/', views.confirmCheckout, name='shoppy-checkout'),

   # useraccount password change
   path('user_account/change_password', views.change_password, name='change_password'),

   # password reset





   path('password_reset/', auth_views.PasswordResetView.as_view(
      template_name='shoppy/registration/password_reset.html',
      email_template_name='shoppy/registration/password_reset_email.html',
      subject_template_name='shoppy/registration/password_reset_subject.txt',
      success_url=reverse_lazy('Shoppy:password_reset_done')
   ), name='password_reset'),

   path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
      template_name='shoppy/registration/password_reset_done.html',
   ), name='password_reset_done'),

   path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
      template_name='shoppy/registration/password_reset_confirm.html',
      success_url=reverse_lazy('Shoppy:password_reset_complete')
   ), name='password_reset_confirm'),

   path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(
      template_name='shoppy/registration/password_reset_complete.html',
   ), name='password_reset_complete'),







]

shoppy/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import *
from django import forms


class BuyerSignUpForm(UserCreationForm):

    class Meta:
        model = Buyer
        fields = ('username','first_name', 'last_name','phone_number','email',)

class BuyerUpdateForm(forms.ModelForm):

    class Meta:
        model = Buyer
        fields = ('username','first_name', 'last_name','phone_number',)







# seller
class SellerSignUpForm(UserCreationForm):

     class Meta:
         model = Seller
         fields = ('email','phone_number','business_no','store_logo','store_name','country','first_name','last_name','username',)

    #seller update form


class SellerUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name','last_name','username',)


class SellerForm(forms.ModelForm):
        class Meta:
            model = Seller
            fields = ('phone_number','business_no','store_logo','store_name','country',)









class ProductForm(forms.ModelForm):

    class Meta:
        model =Product
        fields= ('name', 'unit_cost','product_brand','short_description','long_description','featured_url','seller',)

class ImagesForm(forms.ModelForm):

    class Meta:
        model= Image
        fields=['image', 'product',]




class ProductVariantOptionForm(forms.ModelForm):

    class Meta:
        model= Product_Variant_Options
        fields =['product','variant_options',]



class InventoryForm(forms.ModelForm):

    class Meta:
        model = Inventory
        fields = ['product', 'quantity',]
class AddBrandForm(forms.ModelForm):

    class Meta:
        model =Brand
        fields =['name', 'category',]

class CarouselImageForm(forms.ModelForm):

    class Meta:
        model = Carousel
        fields = ['image','description',]

class RegionsForm(forms.ModelForm):

    class Meta:
        model = Region
        fields = ['name','region_cost','seller']

class VariantForm(forms.ModelForm):

    class Meta:
        model = Variant
        fields = ['name',]

class VariantOptionForm(forms.ModelForm):

    class Meta:
        model = Variant_Option
        fields = ['name','variant',]

class AddToWishList(forms.ModelForm):

    class Meta:
        model = Wishlist
        fields = ['buyer','product']

class OrderProductForm(forms.ModelForm):
     class Meta:
         model = Order_Product
         fields = ['quantity', 'product','buyer','total']

class OrderProductVariantOptionForm(forms.ModelForm):
     class Meta:
         model = OrderProductVariantOption
         fields =['orderProduct','variantOptions']

class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ['name','parent_id']


class OfferForm(forms.ModelForm):

    class Meta:
        model= Offer
        fields = ['offer', 'product', 'discount', 'start_time', 'end_time',]

class ChangePasswordForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['password']

shoppy/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, redirect, render_to_response
from django.contrib.auth import authenticate, logout, login, get_user_model
from django.template import RequestContext
from django.urls import reverse_lazy
from django.utils.crypto import get_random_string
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters

from django.views.generic import View
from django.contrib.auth.models import User
from pylint.checkers.typecheck import _

from shoppy.models import *
from .forms import *
from django.http import HttpResponse, HttpResponseNotFound, request
import datetime

# Create your views here.

def search(request):
    if request.method=="POST":
        search_text = request.POST['search_text']

    else:
        search_text =""
    products = Product.objects.filter(name__contains=search_text)
    context={
        'products': products,
        'search_text': search_text,
    }
    return render_to_response('shoppy/search.html',context)

def home(request):
    user = request.user
    carousels =Carousel.objects.order_by("-created_at")
    products = Product.objects.order_by("?")[:10]
    featured_product = Product.objects.filter(status='FEATURED')
    products_all = Product.objects.all()
    wishlist_count = Wishlist.objects.filter(buyer_id=request.user.id).count()



    context ={
        'title':'Shoppy-Home',
        'user': user,
        'carousels' : carousels,
        'featured_products': featured_product,
        'products': products,
        'products_all':products_all,
        'wishlist_count':wishlist_count,
        # 'categories':categories,
        # 'orderproducts': orderproducts
    }
    return render(request, 'shoppy/home.html', context)

@login_required()
def addToWishlist(request, product_id, source):

    product = Product.objects.filter(id=product_id).first()
    buyer = Buyer.objects.filter(user_ptr_id=request.user.id).first()
    print(buyer)
    print(product)

    if buyer is not None and product is not None:
        Wishlist.objects.create(buyer=buyer, product=product)
        messages.success(request, 'Added successfully')
    else:
        messages.error(request, 'Could not add product')


    source = source.replace('____', '/')
    return redirect(source)


@login_required()
def unWishProduct(request, wishlist_id, source):
    buyer = Buyer.objects.filter(user_ptr_id=request.user.id).first()
    wishlist = Wishlist.objects.filter(id=wishlist_id)
    if buyer is not None:
        wishlist.delete()
        messages.success(request, 'Your Wish Have Been Dumped')
    source = source.replace('____', '/')
    return redirect(source)


@login_required()
def unWish_All_Products(request):
    buyer = Buyer.objects.filter(user_ptr_id=request.user.id).first()
    wishlist = Wishlist.objects.all().filter(buyer_id=request.user.id)
    if buyer is not None:

        wishlist.delete()
        messages.success(request, 'All Your Wishes Have Been Dumped')
    return redirect('Shoppy:shoppy-user_account')

# cart
def cart(request):
    carts = Order_Product.objects.filter(buyer_id=request.user.id)
    print(cart)
    context = {
        'carts' : carts,
        'title': 'Shoppy-Cart',
    }
    return render(request, 'shoppy/cart.html', context)

@login_required()
def addCart(request, product_id):
    print(request.POST['quantity'])
    product = Product.objects.filter(id=product_id).first()
    buyer = Buyer.objects.filter(user_ptr_id=request.user.id).first()

    if request.method == 'POST':
        quantity = request.POST['quantity']
        unit_cost = request.POST['unit_cost']
        total = (float(unit_cost) * float(quantity))
        request.POST = request.POST.copy()
        # request.POST['total'] = total
        request.POST['buyer'] = buyer


        orderProduct = Order_Product.objects.create(
            product=product,
            buyer=buyer,
            quantity=quantity,
            total=total,
        )
        for variantoption in request.POST.getlist('variant_options[]'):
            variant_option = Variant_Option.objects.filter(id=int(variantoption)).first()

            if variant_option is not None:
                OrderProductVariantOption.objects.create(
                    variantOptions=variant_option,
                    orderProduct=orderProduct,
                )

        messages.success(request, 'Product Added To Cart')
        return redirect('Shoppy:shoppy-home')
    return redirect('Shoppy:shoppy-home')

def deleteCartProduct(request, order_id):
    cart_product = Order_Product.objects.filter(id=order_id).first()
    cart_product.delete()
    return redirect("Shoppy:shoppy-cart")


def productDetails(request, product_id):
    product = Product.objects.filter(id=product_id).first()
    images = Image.objects.filter(product= product_id)
    review_images = Image.objects.filter(product=product_id)[:2]
    reviews = Review.objects.filter(product=product).order_by('-created_at')
    product_carts = Product.objects.filter(id=product_id)
    similar_products= Product.objects.filter( product_brand=product.product_brand)

    context={
        'product' : product,
        'images' : images,
        'review_images': review_images,
        'similar_products':similar_products,
        'product_carts': product_carts,
        'reviews': reviews
    }

    return render(request, 'shoppy/product_details.html',context)

def productsList(request):

    return render(request, 'shoppy/view_products/all_products.html')




def productReview(request, product_id):
    buyer = Buyer.objects.filter(user_ptr_id=request.user.id).first()
    product = Product.objects.filter(id=product_id).first()
    print(product_id)
    products = Product.objects.all()
    images = Image.objects.filter(product=product_id)
    review_images = Image.objects.filter(product=product_id)[:2]
    reviews = Review.objects.filter(product=product)
    print(reviews)

    if buyer is not None:
        if request.method == 'POST':
            ratings = request.POST.get('ratings', False)
            comments = request.POST['comments']

            Review.objects.create(
                buyer=buyer,
                product=product,
                ratings=ratings,
                comments=comments,
            )
            messages.success(request, 'Your Review Was Taken')
            return redirect("Shoppy:shoppy_product_details")

    context = {
        'product': product,
        'images': images,
        'review_images': review_images,
        'reviews': reviews,
    }

    messages.error(request,'Only Buyers can Review')
    return render(request, 'shoppy/product_details.html', context)


# def user_account_product(request, product_id):
#     similar =Product.objects.filter(id=product_id).first()
#     product = Product.objects.filter(product_brand=similar.product_brand)
#     context={
#         'product':product,
#     }
#     return render(request, 'shoppy/user_account.html', context)


def user_account(request):
    user = request.user
    buyer = Buyer.objects.filter(user_ptr_id=user.id).first()
    seller = Seller.objects.filter(user_ptr_id=user.id).first()
    wishlist = Wishlist.objects.filter(buyer_id=request.user.id)


    if buyer is not None:
        logged_in_user = 'buyer'
    elif seller is not None:
        logged_in_user = 'seller'

    if request.method == 'POST':
        username = request.POST['username']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        phone_number = request.POST['phone_number']
        if buyer is not None:
            user = User.objects.get(pk=request.user.id)
            user.first_name = first_name
            user.last_name = last_name
            user.username = username
            user.save()
            Buyer.objects.filter(user_ptr_id = user.id).update(
                phone_number = phone_number,
            )
    context ={
        'user': logged_in_user,
        'wishlist': wishlist,
    }
    return render(request,'shoppy/user_account.html',context)




def buyer_register(request):
    user= request.user
    if request.method == 'POST':


        form = BuyerSignUpForm(request.POST)
        print(form)
        if form.is_valid():
            user = form.save(commit=False)
            user.email = request.POST['username']
            user.save()
            messages.success(request, 'Buyer Registered Successfully Now Log In')
            return redirect('Shoppy:shoppy-login')
        else:
            form = BuyerSignUpForm()
            # messages.error(request, 'Form Invalid')
            # return redirect('Shoppy:shoppy-home')
            messages.error(request, 'Buyer Registration Error')
            return render(request,"shoppy/buyer-registration.html",{'form':form})
    context={

    }
    return  render(request,"shoppy/buyer-registration.html",context)


def user_login(request):
    messages = []
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        print(username)
        print(password)
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_staff and user.is_active:
                login(request, user)
                return redirect('ShoppyAdmin:shoppy-admin-home')

            if user.is_active:
                if Buyer.objects.filter(user_ptr_id=user.id).exists():
                    login(request, user)
                    # if Buyer.objects.filter(user_ptr_id=user.id).exists():
                    return redirect('Shoppy:shoppy-home')

shoppy/templates/shoppy/buyer-registration.html
{% extends 'shoppy/layout.html' %}

{% block content %}
    <div class="forms-background" >
      <div class="content-section">
          {% if errors %}
            <ul>
            {% for error in errors %}
              <p class=" alert alert-danger text-white">{{ error }}</p>
            {% endfor %}
            </ul>
          {% endif %}

          {% if messages %}
            <ul class="messages">
              {% for message in messages %}
              <p class=" alert alert-danger text-white" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
              {% endfor %}
            </ul>
          {% endif %}

          {% if form.errors %}
            {% for field in form %}
            {% for error in field.errors %}
            <div class="alert alert-danger">
              <strong class="text-white">{{ error|escape }}</strong>
            </div>
            {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger text-white">
              <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
          {% endif %}

        <h2 class="py-4">Buyer Registration</h2>
            <form class="needs-validation" novalidate action="{% url 'Shoppy:shoppy-buyer-reg' %}" method="POST">
                {% csrf_token %}
                  <div class="">

                    <div class="col-md-12 mb-3">
                      <label for="validationCustom01">First name</label>
                      <input name="first_name" type="text" class="form-control" id="validationCustom01" placeholder="First name"  required>
                      <div class="valid-feedback">
                        Looks good!
                      </div>
                      <div class="invalid-feedback">
                        Enter your First name
                      </div>
                    </div>

                    <div class="col-md-12 mb-3">
                      <label for="validationCustom02">Last name</label>
                      <input name="last_name" type="text" class="form-control" id="validationCustom02" placeholder="Last name"  required>
                      <div class="valid-feedback">
                        Looks good!
                      </div>
                      <div class="invalid-feedback">
                        Enter your Last name
                      </div>
                    </div>

                    <div class="col-md-12 mb-3">
                      <label for="validationCustomUsername">Email</label>
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <span class="input-group-text" id="inputGroupPrepend">@</span>
                        </div>
                        <input name="username" type="email" class="form-control" id="validationCustomUsername" placeholder="Email" aria-describedby="inputGroupPrepend" required><br>
                        <small id="passwordHelpBlock" class="form-text text-muted">
                          Your email must be ...@yyy.com.
                        </small>
                         <div class="invalid-feedback">
                          Please enter your Email.
                        </div>
                        <div class="valid-feedback">
                          Looks even fantastic.
                        </div>
                      </div>
                    </div>

                  </div>
                  <div class="">
                    <div class="col-md-12 mb-3">
                      <label for="validationCustom03">Phone number</label>
                      <input name="phone_number" type="number" class="form-control" id="validationCustom03" placeholder="Phone number" required>
                      <div class="invalid-feedback">
                        Please provide your phone number.
                      </div>
                      <div class="valid-feedback">
                        Nice .
                      </div>
                    </div>

                    <div class="col-md-12 mb-3">
                      <label for="validationCustom04">Password</label>
                      <input type="password" name="password1" class="form-control" id="validationCustom04" placeholder="Password" required>
                        <small id="passwordHelpBlock" class="form-text text-muted">
                          Your password must be 8-20 characters long, contain letters and numbers.
                        </small>
                      <div class="invalid-feedback">
                        Please provide a valid state.
                      </div>
                      <div class="valid-feedback">
                        Better looking.
                      </div>
                    </div>

                    <div class="col-md-12 mb-3">
                      <label for="validationCustom05">Confirm Password</label>
                      <input name="password2" type="password" class="form-control" id="validationCustom05" placeholder="Confirm Password" required>
                        <small id="passwordHelpBlock" class="form-text text-muted">
                          Your password must be 8-20 characters long, contain letters and numbers.
                        </small>
                      <div class="invalid-feedback">
                        Please provide a valid zip.
                      </div>
                      <div class="valid-feedback">
                        Looks Good.
                      </div>
                    </div>

                  </div>

                  <button class="product-button" type="submit">Submit form</button>

                </form>
                <div class=" pt-3">
                    <small class="text-muted medium-text">
                        Already have an account? <a href="{% url 'Shoppy:shoppy-login' %}" class="ml-2">Log In</a>
                    </small>
                    <br>
                    <small class="text-muted medium-text mt-2">
                        Register as a seller? <a href="{% url 'Shoppy:shoppy-seller-reg' %}" class="ml-2">Here</a>
                    </small>
                </div>
    </div>
    </div>
{% endblock content %}

shoppy/templates/shoppy/cart.html
{% extends 'shoppy/layout.html' %}
{% load static %}
{% load call_method %}
{% load humanize %}
{% block content %}

    <div class="col-sm-12 row px-5 d-flex justify-content-center">
        {% if carts %}
        <!-- Editable table -->
            <div class="card cart-container">
              <h3 class="card-header text-left cart-header-text text-uppercase py-4">Cart ({{ carts.count }})</h3>
              <div class="card-body cart-table-body">
                <div id="table" class="table-editable">
                  <span class=" float-right mb-3 mr-2"><a href="{% url "Shoppy:shoppy-home" %}" class="btn btn-outline-warning">Continue Shopping</a>
                  </span>
                  <table class="table table-bordered table-responsive-md table-striped text-center">
                    <thead>
                      <tr>
                        <th class="text-center cart-prod-table-header cdth">Item</th>
                        <th class="text-center cart-prod-table-header">Variant</th>
                        <th class="text-center cart-prod-table-header">Quantity</th>
                        <th class="text-center cart-prod-table-header">Action</th>
                        <th class="text-center cart-prod-table-header">Unit Price</th>
                        <th class="text-center cart-prod-table-header">Total</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for cart in carts %}
                      <!-- This is our clonable table line -->
                      <tr>
                        <td class="pt-3-half d-flex align-items-center " contenteditable="false">
                            <div class="imagescrollimg m-0 position-relative">
                                <img src="{{ cart.product.featured_url.url }}" alt="cartproduct">
                            </div>
                            {% if cart.product.id|product_on_offer %}
                                {% for offer in cart.product.id|product_on_offer %}
                                    <span style="position: absolute; left: 33px;" class="badge badge-danger badge-pill text-white">Save {{ offer.discount }}%</span>
                                {% endfor %}
                            {% endif %}

                            <div class="cart-prod-name-wrapper pl-4">
                                <p class="cart-prod-name-text text-capitalize">{{ cart.product.name|truncatechars:17 }}</p>
                            </div>

                        </td>
                        <td class="pt-3-half  " contenteditable="false">30</td>
                        <td class="pt-3-half d-flex justify-content-center" contenteditable="false">
                            <div class="slider-container">
                                <button class="btn-num-product-down slider-contents slider-contents-control border-right"></button>
                                <input class="slider-contents slider-contents-center num-product d-flex justify-content-center align-items-center slider_count" type="number" name="quantity" value="{{ cart.quantity }}">
                                <button class="btn-num-product-up slider-contents slider-contents-control border-left"></button>
                            </div>
                        </td>
                        <td class="pt-3-half" contenteditable="false">
                            <div>
                                <span class="">
                                    <a href="" class="delete-button"><i class="far fa-heart"></i></a>
                                 </span>
                                 <span class="">
                                    <a href="{% url "Shoppy:shoppy_delete_cart_product" cart.id %}" class="delete-button"><i class="fas fa-trash"></i></a>
                                 </span>
                            </div>
                        </td>
                        <td class="pt-3-half" contenteditable="false">
                            {% if  cart.product.price_after_offer and cart.product.id|product_on_offer %}
                                <div style="display: flex;flex-direction: column;">
                                    <span> {{ cart.product.price_after_offer|floatformat:1|intcomma }}Kshs</span>
                                </div>
                            {% else %}
                                <span style="margin-bottom: 21px"> {{ cart.product.unit_cost|floatformat:1|intcomma }}Kshs</span>
                            {% endif %}

                        </td>
                        <td class="pt-3-half" contenteditable="false">
                            {{ cart.total|floatformat:2|intcomma }} Kshs
                        </td>
                      </tr>
                      <!-- This is our clonable table line -->
                    {% endfor %}

                    </tbody>
                    <tfoot>

                        <tr >
                            <td colspan="4"></td>
                            <td colspan="2">
                                <div class="totals d-flex flex-column justify-content-center">
                                    <span class="sub-totals  py-3 d-flex">
                                        <span class="mr-auto text-dark" >SubTotal </span>
                                        Ksh {{ request.user|total_cost_exclusive_vat|floatformat:1|intcomma  }}
                                    </span>
                                    <span class="sub-totals sub-totals-custom py-3 d-flex">
                                        <span class="mr-auto text-dark">Vat 16%</span>
                                        Ksh {{ request.user|vat_cost|floatformat:1|intcomma  }}
                                    </span>
                                    <span class="sub-totals py-3 d-flex">
                                        <span class="mr-auto text-dark"> Total Cost</span>
                                        Ksh {{ request.user|total_cost_inclusive_of_vat|floatformat:1|intcomma }}
                                    </span>

                                    <a href="{% url 'Shoppy:shoppy-view_checkout' %}" class="product-button text-white mt-4">CheckOut</a>
                                </div>
                            </td>

                        </tr>
                    </tfoot>
                  </table>
                </div>
              </div>
            </div>
        <!-- Editable table -->
        {% else %}
            <div class="card cart-container">
              <h3 class="card-header text-left cart-header-text text-uppercase py-4">Cart (0)</h3>
              <div class="card-body cart-table-body">
                <div id="table" class="table-editable">
                  <span class=" float-right mb-3 mr-2"><a href="{% url "Shoppy:shoppy-home" %}" class="btn btn-outline-warning">Continue Shopping</a>
                  </span>
                    <div class="row mt-2 d-flex justify-content-center align-content-center align-items-center">
                         <div class="col-sm-6" style="width: 200px; border: none;margin: 20px; overflow: hidden;">
                             <h1 class="text-center py-5">No Cart For You Today</h1>
                             <img class="img-fluid w-100 h-100" src="{% static 'img/no wishlist image/nowishlist.png' %}" alt="">
                         </div>
                    </div>
                </div>
              </div>
            </div>

        {% endif %}
    </div>

{% block scripts %}
{#    <script>#}
{#        $('.btn-num-product-down').on('click', function(e){#}
{#        e.preventDefault();#}
{#        var numProduct = Number($(this).next().val());#}
{#        if(numProduct > 1) $(this).next().val(numProduct - 1);#}
{#        });#}
{##}
{#        $('.btn-num-product-up').on('click', function(e){#}
{#            e.preventDefault();#}
{#            var numProduct = Number($(this).prev().val());#}
{#            $(this).prev().val(numProduct + 1);#}
{#        });#}
{#    </script>#}
{% endblock %}


{% endblock content %}